server:
  port: 8085
  
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: tarifa-service
          uri: lb://tarifa-service
          predicates:
            - Path=/tarifa-service/**
          filters:
            - StripPrefix=1
        - id: descuento-personas-service
          uri: lb://DESCUENTO-PERSONAS-SERVICE
          predicates:
            - Path=/descuento-personas-service/**
          filters:
            - StripPrefix=1
        # Agrega más servicios cuando los tengas:
        # - id: reserva-service
        #   uri: lb://reserva-service
        #   predicates:
        #     - Path=/reserva-service/**
        #   filters:
        #     - StripPrefix=1
        # - id: usuario-service
        #   uri: lb://usuario-service
        #   predicates:
        #     - Path=/usuario-service/**
        #   filters:
        #     - StripPrefix=1