server:
  port: 0

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka
  instance:
    preferIPAddress: true

spring:
  datasource:
    url: jdbc:postgresql://reservas2-service:5432/reservas2
    username: postgres
    password: bajoterra
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # ================================
  # CONFIGURACIÓN DE EMAIL - GMAIL (CORREGIDA)
  # ================================
  mail:
    host: smtp.gmail.com
    port: 587
    username: nelson.cereno.lpsj@gmail.com        
    password: iuvs utgp vciv jetu           
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000
        debug: false
    default-encoding: UTF-8
    test-connection: false

# ================================
# CONFIGURACIÓN DE FEIGN (Spring Boot 2.5.4)
# ================================
feign:
  client:
    config:
      default:
        connectTimeout: 10000
        readTimeout: 15000
        loggerLevel: BASIC
        
      tarifa-service:
        connectTimeout: 5000
        readTimeout: 8000
        
      descuento-personas-service:
        connectTimeout: 5000
        readTimeout: 8000
        
      descuento-clientes-service:
        connectTimeout: 5000
        readTimeout: 8000
        
      descuento-cumpleanos-service:
        connectTimeout: 5000
        readTimeout: 8000
        
      cliente-service:
        connectTimeout: 8000
        readTimeout: 12000
        
      kart-service:
        connectTimeout: 8000
        readTimeout: 12000

# ================================
# CONFIGURACIÓN DE LOGGING
# ================================
logging:
  level:
    com.karting: DEBUG
    com.karting.client: DEBUG
    com.karting.service: INFO
    org.springframework.cloud.openfeign: DEBUG
    feign: DEBUG
    org.springframework.mail: DEBUG
    org.hibernate.SQL: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

# ================================
# CONFIGURACIÓN DE ACTUATOR (Spring Boot 2.5.4)
# ================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always