server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-service:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    preferIPAddress: true

spring:
  datasource:
    url: jdbc:postgresql://tarifaduracionreservas-service:5433/tarifaduracionreservas
    username: postgres
    password: bajoterra
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect