apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-service-deployment
  labels:
    app: gateway-service-deployment
spec:
  selector:
    matchLabels:
      app: gateway-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway-service-deployment
    spec:
      containers:
        - name: gateway-service
          image: nelsoncereno/gateway-service
          ports:
            - containerPort: 8085
---

apiVersion: v1
kind: Service
metadata:
  name: gateway-service-service
  labels:
    app: gateway-service-service
spec:
  selector:
    app: gateway-service-deployment
  ports:
    - protocol: TCP
      port: 8085
      targetPort: 8085
      nodePort: 30000
  type: LoadBalancer