apiVersion: apps/v1
kind: Deployment
metadata:
  name: tarifa-service-deployment
  labels:
    app: tarifa-service-deployment
spec:
  selector:
    matchLabels:
      app: tarifa-service-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: tarifa-service-deployment
    spec:
      containers:
        - name: tarifa-service
          image: nelsoncereno/tarifa-service
          ports:
            - containerPort: 8090